export const demoApplications = [
    {
        id: "1",
        company: "Shopify",
        role: "Junior Frontend Developer",
        location: "Toronto, ON",
        status: "Applied",
        jobUrl: "https://shopify.com/careers/",
        notes: "Applied through company careers page. Highlighted react and typescript experience.",
        appliedDate: "2024-05-01",
        updatedDate: "2024-05-02",
    },
    {
        id: "2",
        company: "Google",
        role: "Software Engineer Intern",
        location: "Mountain View, CA",
        status: "Interview",
        jobUrl: "https://careers.google.com/jobs/results/",
        notes: "Referred by a friend. Interview scheduled for next week.",
        appliedDate: "2026-04-15",
        updatedDate: "2026-04-20",
    },
    {
        id: "3",
        company: "TD Bank",
        role: "QA Automation Analyst",
        location: "Montreal, QC",
        status: "Rejected",
        jobUrl: "https://jobs.td.com/jobs/results/",
        notes: "Rejected after second interview. Useful practice but need to improve on coding challenges.",
        appliedDate: "2026-03-18",
        updatedDate: "2026-03-28",
    },
    {
        id: "4",
        company: "Amazon",
        role: "Cloud Support Associate",
        location: "Remote",
        status: "Offer",
        jobUrl: "https://www.amazon.jobs/en/",
        notes: "Received offer with competitive salary and great benefits. Need to decide by end of month.",
        appliedDate: "2026-05-12",
        updatedDate: "2026-05-19",
    }
];